language: php

php:
  - 7.0

before_script:
  - composer self-update
  - composer install --no-interaction

install:
  - pip install codecov

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_sucess: codecov
