language: php

php:
  - 7.0

before_script:
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
